### PR TITLE
[WIP] markup events as microdata

### PR DESCRIPTION
**Pull request by MatMoore**
Calendar pages contain very simple information that could be presented to the user without them even visiting the page.

At the moment, it seems like search engines don't always understand how to use our calendars to answer the user's query directly and GOV.UK is not always the top result (at least for me).

Here's some examples of google doing the wrong thing (the next bank holiday for England and Wales is in December):

screen shot 2016-09-29 at 15 44 30
screen shot 2016-09-29 at 16 30 33
screen shot 2016-09-29 at 16 31 16

screen shot 2016-09-29 at 16 31 36

This branch is an attempt to implement this schema: http://schema.org/Event

WIP HTML:

``` html
                <div class="highlighted-event" itemscope itemtype="http://schema.org/Event">
                  <meta itemprop="location" content="England and Wales">
                  <p>The next bank holiday in England and Wales is</p>
                  <p>
                    <time itemprop="startDate" datetime="2016-12-26">26 December</time>
                    <span itemprop="name">Boxing Day</span>
                  </p>
                </div>
```

This doesn't validate according to https://search.google.com/structured-data/testing-tool/u/0/, although the w3c parser didn't have a problem with it.

I'm not sure if this is a sensible way to deal with "location". I've used a meta tag because it feels like the location is implicit: we only refer to the division in the "in" text and this can differ from the location name:

```
      england-and-wales:      "Cymru a Lloegr"
      england-and-wales_in:   "yng Nghymru a Lloegr"
```

### CODE REVIEW

**Comment by carolinegreen** [comment]
I think it's not validating because you haven't said what itemtype location is and it defaults to 'Thing' the most generic itemtype, which is okay for something like name, but isn't for location.

https://schema.org/location

The other complaints look more like recommendations more than anything.

**Comment by MatMoore** [comment]
@carolinegreen do you have an example that validates? I tried actually adding `itemtype` attribute to the meta tag but couldn't get that to validate either. 😭 

I tried to find a similar example on schema.org but they use a "Thing" as well:

```html
<div itemprop="event" itemscope itemtype="http://schema.org/Event">
  <a href="foo-fighters-may20-fedexforum" itemprop="url">
    <span itemprop="name">FedExForum</span>
  </a>
  <span itemprop="location">Memphis, TN, US</span>
  <meta itemprop="startDate" content="2011-05-20">May 20
  <a href="ticketmaster.com/foofighters/may20-2011" itemprop="offers">Buy tickets</a>
</div>
```

**Comment by carolinegreen** [comment]
@MatMoore Yes, I can, by using the extra information provided in microdata example on the page I linked to.  (It's at the bottom.)  Although the actual example doesn't validate in it's original form.  If you take away the meta tag, and nest an address and name within the location as a tag which accepts nested tags it will validate.  Which I realise defeats the point of using the meta tag in this way. 

The documentation seems pretty dubious on schema org.  I've read conflicting things from other sources as well.  It needs more thought, and I'm still on 2ndline at the moment.

I'm not suggesting we use this at all, but it is an example that validates.

`<div class="highlighted-event" itemscope itemtype="http://schema.org/Event">
    <div itemprop="location" itemscope itemtype="http://schema.org/Place" content="England   and Wales">
      <span itemprop="name">Bank Holiday</span>
      <span itemprop="address">England and Wales</span>
  </div>
    <p>The next bank holiday in England and Wales is</p>
    <p>
       <time itemprop="startDate" datetime="2016-12-26">26 December</time>
       <span itemprop="name">Boxing Day</span>
       </p>
</div>`

**Comment by MatMoore** [comment]
I'm going to close this for now as I haven't had time to look at it in many more detail, and the PR is not mergeable in its current state.

**Pull request closed without merging**
